#!/usr/bin/python3
import sys
from argparse import ArgumentParser

from BMPstat.bmpstat import BMPstat

def embedder(host: str, data: str, out: str, no_zeros: bool):
	print("="*15+" Embedding "+"="*15)

	with open(data, "rb") as f1:
		data = f1.read()

	with open(host, "rb") as f2:
		"""
		Host image is BMPstat parsing
		"""
		host_bmp = BMPstat(f2.read())

	"""
	The data must to be <= data payload of the host image 
	"""
	buf_size = host_bmp.get_payload_size()
	data_size = len(data)

	print(f"INPUT:\n\t[+] Host size: {buf_size} B\n\t[+] Data size: {data_size} B\n")

	padding=buf_size-data_size

	if padding < 0:
		print(f"**Error@Embedding**: the host image size < data size. The difference is {-1*padding}B")
		sys.exit(1)

	_hidden = bytearray(data)
	offset = host_bmp.get_offset()

	if not no_zeros:
		print(f"""[>] Embedding with padding ({padding} bytes of NULL)""")
		_hidden.extend(b'\x00'*padding) 
		host_bmp.set_payload(_hidden)

	else:
		print("""[>] Embedding with byte substitution""")
		host_bmp.raw_image[offset:offset+data_size] = _hidden # BYPASS size check

	with open(out, "wb") as f3:
		f3.write(host_bmp.get_raw_image())

	print(f"\nOUTPUT:\n\t[+] New file {out}\n\t[+] offset: @{offset} B\n\t[+] padding size: {padding} B")

def get_input():
	# Command-line arguments parser
	parser = ArgumentParser(
	prog="BMPembedder", 
	description="Embedder data in BMP file.")

	parser = ArgumentParser(add_help=True)
	parser.add_argument("-i", "--host", help="Host BMP image", type=str, required=True)
	parser.add_argument("-d", "--data", help="File to embed in the host (any type) ", type=str, required=True)
	parser.add_argument("-o", "--output", help="Output filename (BMP)", type=str, required=True)
	parser.add_argument("--no-padding", help="Default padding are NULL bytes, otherwise use HOST data", \
		action="store_true", default=False, required=False)

	try:
		args = parser.parse_args()
	except SystemExit as e:
		print(e)

	host = args.host
	data = args.data
	out = args.output
	no_zeros = args.no_padding

	return host, data, out, no_zeros

if __name__ == "__main__":
	host, data, out, no_zeros = get_input()
	embedder(host, data, out, no_zeros)